Nuevo.WebUI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Nuevo.Business.Abstract;
using Nuevo.WebUI.Models;

namespace Nuevo.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPersonalService _personalService;

        public HomeController(ILogger<HomeController> logger, IPersonalService personalService)
        {
            _logger = logger;
            _personalService = personalService;
        }

        public IActionResult Index()
        {
            var getPersonals = _personalService.GetAll();

            return View(getPersonals);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Nuevo.WebUI/Controllers/PersonalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nuevo.Business.Abstract;
using Nuevo.WebUI.Models;
using System.Collections.Generic;
using Nuevo.Entities.Concrete;
using Nuevo.WebUI.Helpers;

namespace Nuevo.WebUI.Controllers
{
    public class PersonalController : Controller
    {
        private readonly IPersonalService _personalService;
        private readonly IDepartmantService _departmantService;
        private readonly IManagerService _managerService;
        private readonly IUserService _userService;

        public PersonalController(IPersonalService personalService, IDepartmantService departmantService, IManagerService managerService, IUserService userService)
        {
            _personalService = personalService;
            _departmantService = departmantService;
            _managerService = managerService;
            _userService = userService;
        }

        public IActionResult Detail(int? id)
        {
            if (id == null)
                return RedirectToAction("Index", "Home");

            var helpers = new SelectDetails();

            var getUser = _personalService.GetById((int)id);
            var departmantItems = helpers.GetDepartmantItems(getUser, _departmantService);
            var managerItems = helpers.GetManagerItems(getUser, _managerService);
            var username = _userService.GetUserId(getUser.ManagerId).Username;

            if (getUser != null)
            {
                var departmantInfo = _departmantService.GetById(getUser.DepartmantId);
                var managerInfo = _managerService.GetById(getUser.ManagerId);

                var personalDetail = new PersonalDetailView
                {
                    Personal = getUser,
                    Departmant = departmantInfo,
                    Manager = managerInfo,
                    Departmants = departmantItems,
                    Managers = managerItems,
                    isDisabled = username == User.Identity.Name ? true : false
                };

                return View(personalDetail);
            }

            ViewBag.userNotFound = "User is not exist";
            return View();
        }
    }
}

Nuevo.WebUI/Views/Home/Index.cshtml
@using Nuevo.Entities.Concrete
@{
    ViewData["Title"] = "Public UI - Everyone can see this page";
}

@model IList<Personal>

<div class="row col-12">
    @foreach (var personal in Model)
    {
        <div class="card text-center col-5 m-auto" style="margin-top: 10px !important">
            <div class="card-body">
                <h4 class="card-title">Personal Informations</h4>
                <hr />
                <table class="table table-borderless table-hover table-responsive-sm table-responsive-md">
                    <tr>
                        <th>Name</th>
                        <th>Phone</th>
                    </tr>
                    <tr>
                        <td>
                            @personal.Name
                        </td>
                        <td>
                            @personal.PhoneNumber
                        </td>
                    </tr>
                </table>
                <a asp-controller="Personal" asp-action="Detail" asp-route-id="@personal.Id" class="card-link">Details...</a>
            </div>
        </div>

    }
</div>